#!/bin/sh

set -o pipefail
set -o nounset

for file in `ls *.HEIC *.heic`
do
  echo "Converting $file to ${file%.heic}.jpg ..."
  heif-convert -q 100 "$file" "${file%.heic}.jpg"
  if [ $? -eq 0 ]
    then
      rm "${file}"
  else
      echo "ERROR: ${file%.heic}.jpg"
  fi
done