name: heif-convert

on:
  push:
    paths:
    - 'heif-convert/**'
    - '.github/workflows/heif-convert.yml'
  schedule:
    - cron:  '0 5 15,25 * *'
  repository_dispatch:
    types: [heif-convert]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: heif-convert/.
          push: true
          tags: sfragata/heif-convert:latest