name: nodejs

on:
  push:
    paths:
    - 'nodejs/**'
    - '.github/workflows/nodejs.yml'
  schedule:
    - cron:  '0 5 15,25 * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: nodejs/.
          platforms: linux/amd64,linux/arm64
          push: true
          provenance: mode=min
          sbom: true
          tags: sfragata/nodejs:latest