name: plex_exporter

on:
  push:
    paths:
    - 'plex_exporter/**'
    - '.github/workflows/plex_exporter.yml'
  schedule:
    - cron:  '0 5 15,25 * *'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: set artifact version
        run: |
          echo "artifact_id=$(curl -s https://api.github.com/repos/sfragata/plex_exporter/releases/latest | grep browser_download_url | head -n 1 | grep -Eo 'v[0-9].[0-9].[0-9]')" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: plex_exporter/.
          push: true
          tags: sfragata/plex_exporter:latest, sfragata/plex_exporter:${{ env.artifact_id }}
      -
        name: Build and push tag
        if: github.event.action == 'plex_exporter'
        uses: docker/build-push-action@v5
        with:
          context: plex_exporter/.
          push: true
          tags: sfragata/plex_exporter:${{ github.event.client_payload.image_version }}          