name: plex_exporter

on:
  push:
    paths:
    - 'plex_exporter/**'
    - '.github/workflows/plex_exporter.yml'
  schedule:
    - cron:  '0 5 15,25 * *'
  repository_dispatch:
    types: [plex_exporter]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: plex_exporter/.
          push: true
          tags: sfragata/plex_exporter:latest
      -
        name: Build and push tag
        if: github.event.action == 'plex_exporter'
        uses: docker/build-push-action@v2
        with:
          context: plex_exporter/.
          push: true
          tags: sfragata/plex_exporter:${{ github.event.client_payload.image_version }}          